### ISSUE TITLE
No way of knowing version from the GUI

### ISSUE THREAD

**Issue by petefreestone** [easy-electrophysiology/easy-electrophysiology-analysis#1]
There is no way of finding the version from the GUI. Most applications provide this information in a 'About' window - along with additional links and contact information.

I propose adding an About window, and the corresponding menu item.

**Comment by easy-electrophysiology** [comment]
Thanks a lot for this suggestion, that's a great idea. This will be added to the next version. For now (although it is not ideal) the version number can be found in the version.md file located in the installation folder.

The website / contact details and current version will be included in this window.  If you have any other suggestions of information you think would be useful it would be great to hear.

**Comment by easy-electrophysiology** [comment]
Thanks again for this suggestion, this has been added to v2.4.0.

**Comment by easy-electrophysiology** [comment]
Implemented in v.2.40
