### ISSUE TITLE
Loading multiple files and concatenating

### ISSUE THREAD

**Issue by thomclarke** [easy-electrophysiology/easy-electrophysiology-analysis#5]
To avoid issues with buffering and losing data in the event of a crash, we record ~50s long abf files during experiments.

It would be really useful if Easy-Electrophysiology allowed loading multiple files and concatenating them together for analysis of activity over a long period of time (some of our recordings are ~30mins long).

Is this is feature that could be added?

**Comment by easy-electrophysiology** [comment]
Thanks for the suggestion, this could be added to load multiple files at once and concatenate them together. 

The simplest way to load would be for each file to be a different record. The times could be concatenated (e.g. 2 50s recordings would be concatanated to 2 50s record, record 1 0 - 50s and record 2 50-100 s). This may be optimal as the inter-event intervals are not calculated across record in Easy Electrophysiology. If these files were concatanated into a single recording, the last event of the first file and first event of the second file would have an inter-event interval that may not be reflective of reality, unless the two files were recorded with 0 delay between them.

Then, there would always be the option to concatate the records into one long record if desired (using Data> Reshape Records).

If this sounds good, it could most likely be added to the next version release.

**Comment by thomclarke** [comment]
There isn't a delay between file recordings, so your suggestion of concatenating files into a single recording would be excellent thank you!

**Comment by easy-electrophysiology** [comment]
Hi @thomclarke, apologies for the long delay in response, there were some unexpected setbacks in finalising v.2.5.0 (now released) and this new feature was scheduled to be implemented in v2.6.0. A v2.6.0 pre-release including this feature will be made available soon. Thanks for your patience!

**Comment by easy-electrophysiology** [comment]
Hi Tom, thanks again for this suggestion. This feature is now available in the the [v2.6.0-pre-release](https://www.easyelectrophysiology.com/v2-6-0-pre-release)
